[all]
proxy.pprod.webgerest ansible_host=51.91.97.12 ansible_user=ianord

[all:vars]
registry_hostname=sb07qkc1.gra7.container-registry.ovh.net
registry_username={{ vault_harbor_username }}
registry_password={{ vault_harbor_password }}

[all:children]
proxy

[proxy:hosts]
proxy.pprod.webgerest

[proxy:vars]
services_local_storage_folder="/containers/docker"
