"""
Schémas des 31 tables Webgerest (préfixe wg_).

Chaque TableSchema contient :
- columns          : définition DDL (CREATE TABLE)
- partitioning     : partition Iceberg (login_site pour la plupart)
- primary_keys     : clés pour le MERGE/upsert (toujours ["pk"] sauf login/descfic)
- pk_source_columns: colonnes business (hors site_column) concaténées pour former pk
- column_updates   : colonne de borne incrémentale (None = full reload par site)
- column_renames   : renommages post-snake_case {nom_api: nom_trino}
- api_table_name   : route API si différente du nom du dict (ex: "detailarticle")
- code_site_from_api: True si code_site est dans la réponse API (plandis uniquement)
- site_column      : colonne injectée avec le login ("login_site" par défaut)
- date_formats     : format strptime non-standard par colonne

Tables SQL (agrégations depuis d'autres tables Webgerest — pas de fetch API) :
    stats_fcj59, stats_fcj59_detail, stats_recap_site, stat_effect_cred_1,
    stats_dashboard_effect, stats_liv, stats_liv59, stats_liv_mois,
    stats_liv_annee, stats_dashboard
    → Ces tables ont un schéma DDL mais pas de métadonnées de fetch.
"""

from data_process.process.ddl import ColumnDef, TableSchema

WEBGEREST_SCHEMAS: dict[str, TableSchema] = {

    # ── Tables spéciales (jobs dédiés) ───────────────────────────────────────

    "login": TableSchema(
        primary_keys=["login"],
        columns=[
            ColumnDef("login", "VARCHAR"),
            ColumnDef("logingroupe", "VARCHAR"),
            ColumnDef("nometabs", "VARCHAR"),
            ColumnDef("ville", "VARCHAR"),
            ColumnDef("datactif", "DATE"),
            ColumnDef("datinactif", "DATE"),
            ColumnDef("fictif", "BOOLEAN"),
            ColumnDef("statut", "BIGINT"),
            ColumnDef("code_site", "BIGINT"),
            ColumnDef("profil", "BIGINT"),
            ColumnDef("secteur", "BIGINT"),
            ColumnDef("cheminbdd", "VARCHAR"),
            ColumnDef("gestionnaire", "BOOLEAN"),
            ColumnDef("souslogingroupe", "VARCHAR"),
            ColumnDef("id_arrondissement", "BIGINT"),
            ColumnDef("id_canton", "BIGINT"),
            ColumnDef("code_postal", "BIGINT"),
        ],
        date_formats={"datactif": "%Y%m%d", "datinactif": "%Y%m%d"},
    ),

    "descfic": TableSchema(
        primary_keys=["nomfic", "login_group"],
        site_column="login_group",
        columns=[
            ColumnDef("nomfic", "VARCHAR"),
            ColumnDef("statut", "BIGINT"),
            ColumnDef("login_group", "VARCHAR"),
            ColumnDef("description", "VARCHAR"),
        ],
    ),

    # ── Tables de référence (full reload par site/groupe) ────────────────────

    "article": TableSchema(
        partitioning=["login_site"],
        primary_keys=["pk"],
        pk_source_columns=["arcleunik"],
        column_updates="datmod",
        column_renames={"usart_vers_ufa": "usart_vers_ufam"},
        date_formats={"dcreart": "%Y%m%d"},
        columns=[
            ColumnDef("pk", "VARCHAR"),
            ColumnDef("login_site", "VARCHAR"),
            ColumnDef("arcleunik", "BIGINT"),
            ColumnDef("codart", "BIGINT"),
            ColumnDef("libart", "VARCHAR"),
            ColumnDef("codfamart", "VARCHAR"),
            ColumnDef("sfaart", "VARCHAR"),
            ColumnDef("usart", "VARCHAR"),
            ColumnDef("dpaart", "DOUBLE"),
            ColumnDef("pmpart", "DOUBLE"),
            ColumnDef("qtethe", "DOUBLE"),
            ColumnDef("qtecom", "DOUBLE"),
            ColumnDef("dcreart", "DATE"),
            ColumnDef("slqte", "DOUBLE"),
            ColumnDef("codstk", "VARCHAR"),
            ColumnDef("codtva", "VARCHAR"),
            ColumnDef("conditionne", "BOOLEAN"),
            ColumnDef("suivi", "BOOLEAN"),
            ColumnDef("percde", "BIGINT"),
            ColumnDef("delai", "BIGINT"),
            ColumnDef("reglecalc", "BIGINT"),
            ColumnDef("catol", "VARCHAR"),
            ColumnDef("pdsbrut", "DOUBLE"),
            ColumnDef("glucides", "DOUBLE"),
            ColumnDef("lipides", "DOUBLE"),
            ColumnDef("protides", "DOUBLE"),
            ColumnDef("energie", "DOUBLE"),
            ColumnDef("qtecomus", "DOUBLE"),
            ColumnDef("reglearr", "BIGINT"),
            ColumnDef("uniteft", "VARCHAR"),
            ColumnDef("seuilmaxi", "DOUBLE"),
            ColumnDef("nature", "BIGINT"),
            ColumnDef("pdsvol", "DOUBLE"),
            ColumnDef("statut", "BIGINT"),
            ColumnDef("datmod", "TIMESTAMP(6)"),
            ColumnDef("id_marche", "BIGINT"),
            ColumnDef("id_lots", "BIGINT"),
            ColumnDef("bio", "BOOLEAN"),
            ColumnDef("designation_externe", "VARCHAR"),
            ColumnDef("allergenes", "VARCHAR"),
            ColumnDef("codarticle", "VARCHAR"),
            ColumnDef("usart_vers_ufam", "DOUBLE"),
            ColumnDef("logincrea", "VARCHAR"),
            ColumnDef("descfic_statut", "BIGINT"),
        ],
    ),

    "categ": TableSchema(
        partitioning=["login_site"],
        primary_keys=["pk"],
        pk_source_columns=["codcat"],
        columns=[
            ColumnDef("pk", "VARCHAR"),
            ColumnDef("login_site", "VARCHAR"),
            ColumnDef("codimp", "BIGINT"),
            ColumnDef("famcat", "BIGINT"),
            ColumnDef("libcat", "VARCHAR"),
            ColumnDef("nbjsem", "BIGINT"),
            ColumnDef("noncompte", "BOOLEAN"),
            ColumnDef("onilait", "BOOLEAN"),
            ColumnDef("ordre", "BIGINT"),
            ColumnDef("regime", "BIGINT"),
            ColumnDef("service", "VARCHAR"),
            ColumnDef("statut", "BIGINT"),
            ColumnDef("typfac", "BIGINT"),
            ColumnDef("codcat", "VARCHAR"),
            ColumnDef("descfic_statut", "BIGINT"),
        ],
    ),

    "detail_article": TableSchema(
        partitioning=["login_site"],
        primary_keys=["pk"],
        pk_source_columns=["id_detailarticle"],
        api_table_name="detailarticle",
        columns=[
            ColumnDef("pk", "VARCHAR"),
            ColumnDef("login_site", "VARCHAR"),
            ColumnDef("id_detailarticle", "BIGINT"),
            ColumnDef("arcleunik", "BIGINT"),
            ColumnDef("circuit_court", "BOOLEAN"),
            ColumnDef("saison_deb", "BIGINT"),
            ColumnDef("saison_fin", "BIGINT"),
            ColumnDef("id_label", "BIGINT"),
            ColumnDef("id_origine", "BIGINT"),
            ColumnDef("codart", "BIGINT"),
            ColumnDef("zinc", "DOUBLE"),
            ColumnDef("fer", "DOUBLE"),
            ColumnDef("iode", "DOUBLE"),
            ColumnDef("selenium", "DOUBLE"),
            ColumnDef("dha", "DOUBLE"),
            ColumnDef("epa", "DOUBLE"),
            ColumnDef("vit_b3", "DOUBLE"),
            ColumnDef("vit_b6", "DOUBLE"),
            ColumnDef("vit_b12", "DOUBLE"),
            ColumnDef("vit_d", "DOUBLE"),
            ColumnDef("id_calories", "BIGINT"),
            ColumnDef("calcium", "DOUBLE"),
            ColumnDef("sodium", "DOUBLE"),
            ColumnDef("sucre", "DOUBLE"),
            ColumnDef("glucose", "DOUBLE"),
            ColumnDef("amidon", "DOUBLE"),
            ColumnDef("fibre", "DOUBLE"),
            ColumnDef("vit_c", "DOUBLE"),
            ColumnDef("magnesium", "DOUBLE"),
            ColumnDef("vit_e", "DOUBLE"),
            ColumnDef("vit_b2", "DOUBLE"),
            ColumnDef("cuivre", "DOUBLE"),
            ColumnDef("vit_a_retinol", "DOUBLE"),
            ColumnDef("vit_k", "DOUBLE"),
            ColumnDef("vit_b9", "DOUBLE"),
            ColumnDef("potassium", "DOUBLE"),
            ColumnDef("phosphore", "DOUBLE"),
            ColumnDef("vit_b1", "DOUBLE"),
            ColumnDef("vit_a_beta_caro", "DOUBLE"),
            ColumnDef("vit_b5", "DOUBLE"),
            ColumnDef("favori", "BOOLEAN"),
            ColumnDef("jamais_local", "BOOLEAN"),
            ColumnDef("acide_gras_sature", "DOUBLE"),
            ColumnDef("descfic_statut", "BIGINT"),
        ],
    ),

    "famart": TableSchema(
        partitioning=["login_site"],
        primary_keys=["pk"],
        pk_source_columns=["codfamart"],
        columns=[
            ColumnDef("pk", "VARCHAR"),
            ColumnDef("login_site", "VARCHAR"),
            ColumnDef("codfamart", "VARCHAR"),
            ColumnDef("libfamart", "VARCHAR"),
            ColumnDef("typart", "BIGINT"),
            ColumnDef("cptfam_1", "VARCHAR"),
            ColumnDef("cptfam_2", "VARCHAR"),
            ColumnDef("cptfam_3", "VARCHAR"),
            ColumnDef("cptfam_4", "VARCHAR"),
            ColumnDef("cptfam_5", "VARCHAR"),
            ColumnDef("cptfam_6", "VARCHAR"),
            ColumnDef("cptfam_7", "VARCHAR"),
            ColumnDef("cptfam_8", "VARCHAR"),
            ColumnDef("cptfam_9", "VARCHAR"),
            ColumnDef("cptfam_10", "VARCHAR"),
            ColumnDef("type", "BIGINT"),
            ColumnDef("statut", "BOOLEAN"),
            ColumnDef("ordre", "BIGINT"),
            ColumnDef("jamais_local", "BOOLEAN"),
            ColumnDef("descfic_statut", "BIGINT"),
        ],
    ),

    "fourn": TableSchema(
        site_column="login_site",
        primary_keys=["pk"],
        pk_source_columns=["f_ocleunik"],
        column_renames={"label": "id_label"},
        columns=[
            ColumnDef("pk", "VARCHAR"),
            ColumnDef("f_ocleunik", "BIGINT"),
            ColumnDef("codfou", "VARCHAR"),
            ColumnDef("login_site", "VARCHAR"),
            ColumnDef("libfou", "VARCHAR"),
            ColumnDef("codfamfou", "VARCHAR"),
            ColumnDef("cpfou", "VARCHAR"),
            ColumnDef("minfac", "DOUBLE"),
            ColumnDef("jours", "VARCHAR"),
            ColumnDef("delai", "BIGINT"),
            ColumnDef("numcli", "VARCHAR"),
            ColumnDef("percde", "BIGINT"),
            ColumnDef("statut", "BIGINT"),
            ColumnDef("login", "VARCHAR"),
            ColumnDef("circuit_court", "BOOLEAN"),
            ColumnDef("num_agrement", "VARCHAR"),
            ColumnDef("bio", "BOOLEAN"),
            ColumnDef("no_engagement", "VARCHAR"),
            ColumnDef("id_fourn_ext", "BIGINT"),
            ColumnDef("id_origine", "BIGINT"),
            ColumnDef("id_label", "BIGINT"),
            ColumnDef("tags", "VARCHAR"),
            ColumnDef("agrimer_fl", "BOOLEAN"),
            ColumnDef("agrimer_lait", "BOOLEAN"),
            ColumnDef("circuit_court_strict", "BOOLEAN"),
            ColumnDef("descfic_statut", "BIGINT"),
        ],
    ),

    "label": TableSchema(
        partitioning=["login_site"],
        primary_keys=["pk"],
        pk_source_columns=["id_label"],
        columns=[
            ColumnDef("pk", "VARCHAR"),
            ColumnDef("login_site", "VARCHAR"),
            ColumnDef("code", "BIGINT"),
            ColumnDef("id_label", "BIGINT"),
            ColumnDef("label", "VARCHAR"),
            ColumnDef("egalim", "BOOLEAN"),
            ColumnDef("descfic_statut", "BIGINT"),
        ],
    ),

    "ntarif": TableSchema(
        partitioning=["login_site"],
        primary_keys=["pk"],
        pk_source_columns=["id_ntarif"],
        columns=[
            ColumnDef("pk", "VARCHAR"),
            ColumnDef("login_site", "VARCHAR"),
            ColumnDef("id_ntarif", "BIGINT"),
            ColumnDef("exercice", "VARCHAR"),
            ColumnDef("codcli", "BIGINT"),
            ColumnDef("codcat", "VARCHAR"),
            ColumnDef("typfac", "BIGINT"),
            ColumnDef("codimp", "BIGINT"),
            ColumnDef("creditbrut", "VARCHAR"),
            ColumnDef("creditnet", "VARCHAR"),
            ColumnDef("forfaitan", "DOUBLE"),
            ColumnDef("forfaittrim", "VARCHAR"),
            ColumnDef("coeftrim", "VARCHAR"),
            ColumnDef("nbjan", "BIGINT"),
            ColumnDef("nbjtrim", "VARCHAR"),
            ColumnDef("nbjsem", "BIGINT"),
            ColumnDef("coefserv", "VARCHAR"),
            ColumnDef("statut", "BIGINT"),
            ColumnDef("prestation", "VARCHAR"),
            ColumnDef("descfic_statut", "BIGINT"),
        ],
    ),

    "sfaart": TableSchema(
        partitioning=["login_site"],
        primary_keys=["pk"],
        pk_source_columns=["codfamart", "sfaart"],
        columns=[
            ColumnDef("pk", "VARCHAR"),
            ColumnDef("login_site", "VARCHAR"),
            ColumnDef("codfamart", "VARCHAR"),
            ColumnDef("sfaart", "VARCHAR"),
            ColumnDef("libsfaart", "VARCHAR"),
            ColumnDef("typart", "BIGINT"),
            ColumnDef("unite", "VARCHAR"),
            ColumnDef("type", "BIGINT"),
            ColumnDef("statut", "BOOLEAN"),
            ColumnDef("ordre", "BIGINT"),
            ColumnDef("jamais_local", "BOOLEAN"),
            ColumnDef("descfic_statut", "BIGINT"),
        ],
    ),

    "trimestre": TableSchema(
        partitioning=["login_site"],
        primary_keys=["pk"],
        pk_source_columns=["notrim", "exercice"],
        columns=[
            ColumnDef("pk", "VARCHAR"),
            ColumnDef("login_site", "VARCHAR"),
            ColumnDef("exercice", "VARCHAR"),
            ColumnDef("datdeb", "DATE"),
            ColumnDef("datfin", "DATE"),
            ColumnDef("notrim", "BIGINT"),
            ColumnDef("nbjtrim", "BIGINT"),
            ColumnDef("descfic_statut", "BIGINT"),
        ],
    ),

    "typss1": TableSchema(
        partitioning=["login_site"],
        primary_keys=["pk"],
        pk_source_columns=["codss1"],
        columns=[
            ColumnDef("pk", "VARCHAR"),
            ColumnDef("login_site", "VARCHAR"),
            ColumnDef("libss1", "VARCHAR"),
            ColumnDef("onilait", "BOOLEAN"),
            ColumnDef("codcpt", "VARCHAR"),
            ColumnDef("boolsh", "BOOLEAN"),
            ColumnDef("id_catpresta", "BIGINT"),
            ColumnDef("no_variante", "BIGINT"),
            ColumnDef("ordre", "BIGINT"),
            ColumnDef("codss1", "VARCHAR"),
            ColumnDef("descfic_statut", "BIGINT"),
        ],
    ),

    "typss2": TableSchema(
        partitioning=["login_site"],
        primary_keys=["pk"],
        pk_source_columns=["codss2"],
        columns=[
            ColumnDef("pk", "VARCHAR"),
            ColumnDef("login_site", "VARCHAR"),
            ColumnDef("libss2", "VARCHAR"),
            ColumnDef("bool_supprimable", "BOOLEAN"),
            ColumnDef("statut", "BIGINT"),
            ColumnDef("codss2", "VARCHAR"),
            ColumnDef("descfic_statut", "BIGINT"),
        ],
    ),

    # ── Tables opérationnelles (upsert incrémental) ───────────────────────────

    "effect": TableSchema(
        partitioning=["login_site"],
        primary_keys=["pk"],
        pk_source_columns=["id_effect"],
        column_updates="efdate",
        column_renames={"efcleunik": "id_effect"},
        columns=[
            ColumnDef("pk", "VARCHAR"),
            ColumnDef("login_site", "VARCHAR"),
            ColumnDef("efdate", "DATE"),
            ColumnDef("id_effect", "BIGINT"),
            ColumnDef("eftheo", "BIGINT"),
            ColumnDef("efreel", "BIGINT"),
            ColumnDef("efprev", "BIGINT"),
            ColumnDef("credit", "DOUBLE"),
            ColumnDef("codcat", "VARCHAR"),
            ColumnDef("typfac", "BIGINT"),
            ColumnDef("codcli", "BIGINT"),
            ColumnDef("effautre", "BIGINT"),
            ColumnDef("creditbrut", "DOUBLE"),
            ColumnDef("origine", "VARCHAR"),
            ColumnDef("date_import", "DATE"),
            ColumnDef("date_modif", "DATE"),
            ColumnDef("codss1", "VARCHAR"),
            ColumnDef("codss2", "VARCHAR"),
            ColumnDef("descfic_statut", "BIGINT"),
        ],
    ),

    "feuille": TableSchema(
        partitioning=["login_site"],
        primary_keys=["pk"],
        pk_source_columns=["fecleunik"],
        columns=[
            ColumnDef("pk", "VARCHAR"),
            ColumnDef("login_site", "VARCHAR"),
            ColumnDef("fecleunik", "BIGINT"),
            ColumnDef("efdate", "DATE"),
            ColumnDef("codss1", "VARCHAR"),
            ColumnDef("menu", "VARCHAR"),
            ColumnDef("commentaire", "VARCHAR"),
            ColumnDef("codss2", "VARCHAR"),
            ColumnDef("cle_jps", "VARCHAR"),
            ColumnDef("nb_vegetarien", "BIGINT"),
            ColumnDef("type_menu", "VARCHAR"),
            ColumnDef("id_animation", "VARCHAR"),
            ColumnDef("descfic_statut", "BIGINT"),
        ],
    ),

    "gaspi_saisie_gen": TableSchema(
        partitioning=["login_site"],
        primary_keys=["pk"],
        pk_source_columns=["id_gaspi_saisie_gen"],
        column_updates="datej",
        columns=[
            ColumnDef("pk", "VARCHAR"),
            ColumnDef("login_site", "VARCHAR"),
            ColumnDef("id_gaspi_saisie_gen", "BIGINT"),
            ColumnDef("datej", "DATE"),
            ColumnDef("codss1", "VARCHAR"),
            ColumnDef("codss2", "VARCHAR"),
            ColumnDef("qte_gen", "DOUBLE"),
            ColumnDef("cle_jps", "VARCHAR"),
            ColumnDef("eff_prev", "BIGINT"),
            ColumnDef("pas_de_tri", "BOOLEAN"),
            ColumnDef("commentaire", "VARCHAR"),
            ColumnDef("eff_prod", "BIGINT"),
            ColumnDef("eff_reel_service", "BIGINT"),
            ColumnDef("descfic_statut", "BIGINT"),
        ],
    ),

    "mvtart": TableSchema(
        partitioning=["login_site"],
        primary_keys=["pk"],
        pk_source_columns=["mvcleunik"],
        column_updates="dtemvt",
        columns=[
            ColumnDef("pk", "VARCHAR"),
            ColumnDef("login_site", "VARCHAR"),
            ColumnDef("mvcleunik", "BIGINT"),
            ColumnDef("dtemvt", "TIMESTAMP(6)"),
            ColumnDef("typmvt", "BIGINT"),
            ColumnDef("stypmvt", "VARCHAR"),
            ColumnDef("nobon", "VARCHAR"),
            ColumnDef("f_ocleunik", "BIGINT"),
            ColumnDef("arcleunik", "BIGINT"),
            ColumnDef("c0_cleunik", "BIGINT"),
            ColumnDef("qteart", "DOUBLE"),
            ColumnDef("codun", "VARCHAR"),
            ColumnDef("prixht", "DOUBLE"),
            ColumnDef("poremise", "DOUBLE"),
            ColumnDef("taux_tva", "DOUBLE"),
            ColumnDef("pmpart", "DOUBLE"),
            ColumnDef("uatous", "DOUBLE"),
            ColumnDef("e0_cleunik", "BIGINT"),
            ColumnDef("etat", "BIGINT"),
            ColumnDef("trv", "VARCHAR"),
            ColumnDef("numlot", "VARCHAR"),
            ColumnDef("dlc", "DATE"),
            ColumnDef("libart", "VARCHAR"),
            ColumnDef("usart", "VARCHAR"),
            ColumnDef("qteusart", "DOUBLE"),
            ColumnDef("valide", "BOOLEAN"),
            ColumnDef("pcb", "DOUBLE"),
            ColumnDef("totht", "DOUBLE"),
            ColumnDef("totttc", "DOUBLE"),
            ColumnDef("pmpart_ttc", "DOUBLE"),
            ColumnDef("qtefac", "DOUBLE"),
            ColumnDef("pufac", "DOUBLE"),
            ColumnDef("codate", "VARCHAR"),
            ColumnDef("e0_codart", "VARCHAR"),
            ColumnDef("e0_libart", "VARCHAR"),
            ColumnDef("uatoufac", "DOUBLE"),
            ColumnDef("ufac", "VARCHAR"),
            ColumnDef("qtef", "DOUBLE"),
            ColumnDef("puf", "DOUBLE"),
            ColumnDef("stockavant", "DOUBLE"),
            ColumnDef("pmp_avt", "DOUBLE"),
            ColumnDef("dteimp", "DATE"),
            ColumnDef("id_article_lot", "BIGINT"),
            ColumnDef("reference", "VARCHAR"),
            ColumnDef("circuit_court", "BOOLEAN"),
            ColumnDef("id_origine", "BIGINT"),
            ColumnDef("id_label", "BIGINT"),
            ColumnDef("echantillon", "BOOLEAN"),
            ColumnDef("commentaire", "VARCHAR"),
            ColumnDef("bio", "BOOLEAN"),
            ColumnDef("chemin_pj", "VARCHAR"),
            ColumnDef("statut_dlc", "BOOLEAN"),
            ColumnDef("codss1", "VARCHAR"),
            ColumnDef("codss2", "VARCHAR"),
            ColumnDef("descfic_statut", "BIGINT"),
        ],
    ),

    "mvtart_det": TableSchema(
        partitioning=["login_site"],
        primary_keys=["pk"],
        pk_source_columns=["id_mvtart_det"],
        columns=[
            ColumnDef("pk", "VARCHAR"),
            ColumnDef("login_site", "VARCHAR"),
            ColumnDef("id_mvtart_det", "BIGINT"),
            ColumnDef("mvcleunik", "BIGINT"),
            ColumnDef("modif_local", "BOOLEAN"),
            ColumnDef("modif_bio", "BOOLEAN"),
            ColumnDef("modif_label1", "BOOLEAN"),
            ColumnDef("modif_origine", "BOOLEAN"),
            ColumnDef("descfic_statut", "BIGINT"),
        ],
    ),

    "plandis": TableSchema(
        partitioning=["login_site"],
        primary_keys=["pk"],
        pk_source_columns=["plcleunik"],
        column_updates="datdis",
        code_site_from_api=True,   # code_site vient de l'API (CodeSite), pas du login row
        date_formats={"datdis": "%Y%m%d"},
        columns=[
            ColumnDef("pk", "VARCHAR"),
            ColumnDef("login_site", "VARCHAR"),
            ColumnDef("plcleunik", "INTEGER"),
            ColumnDef("an", "VARCHAR"),
            ColumnDef("semaine", "VARCHAR"),
            ColumnDef("jour", "VARCHAR"),
            ColumnDef("service", "VARCHAR"),
            ColumnDef("datdis", "DATE"),
            ColumnDef("effectif", "INTEGER"),
            ColumnDef("prestation", "VARCHAR"),
            ColumnDef("code_site", "INTEGER"),
            ColumnDef("descfic_statut", "BIGINT"),
        ],
    ),

    "detpland": TableSchema(
        partitioning=["login_site"],
        primary_keys=["pk"],
        pk_source_columns=["d1_cleunik"],
        column_updates="datfab",
        columns=[
            ColumnDef("pk", "VARCHAR"),
            ColumnDef("login_site", "VARCHAR"),
            ColumnDef("d1_cleunik", "BIGINT"),
            ColumnDef("typrec", "VARCHAR"),
            ColumnDef("ordre", "VARCHAR"),
            ColumnDef("codrec", "BIGINT"),
            ColumnDef("plcleunik", "BIGINT"),
            ColumnDef("datfab", "DATE"),
            ColumnDef("datbes", "DATE"),
            ColumnDef("codft", "BIGINT"),
            ColumnDef("typord", "VARCHAR"),
            ColumnDef("recleuniq", "VARCHAR"),
            ColumnDef("id_mvtpre", "BIGINT"),
            ColumnDef("puht", "DOUBLE"),
            ColumnDef("puttc", "DOUBLE"),
            ColumnDef("typpart", "BIGINT"),
            ColumnDef("valsor", "BOOLEAN"),
            ColumnDef("options", "BOOLEAN"),
            ColumnDef("potage", "BOOLEAN"),
            ColumnDef("equillibre", "BOOLEAN"),
            ColumnDef("horsgamme", "BOOLEAN"),
            ColumnDef("intolerance", "BOOLEAN"),
            ColumnDef("no_variante", "BIGINT"),
            ColumnDef("recleunik_variante", "VARCHAR"),
            ColumnDef("qtefab", "VARCHAR"),
            ColumnDef("menus", "VARCHAR"),
            ColumnDef("qtemodif", "VARCHAR"),
            ColumnDef("qteprev", "VARCHAR"),
            ColumnDef("qtefabr1", "VARCHAR"),
            ColumnDef("qtefabr2", "VARCHAR"),
            ColumnDef("qtefabr3", "VARCHAR"),
            ColumnDef("qtemodifr1", "VARCHAR"),
            ColumnDef("qtemodifr2", "VARCHAR"),
            ColumnDef("qtemodifr3", "VARCHAR"),
            ColumnDef("taux_prise", "DOUBLE"),
            ColumnDef("descfic_statut", "BIGINT"),
        ],
    ),

    "fitech": TableSchema(
        partitioning=["login_site"],
        primary_keys=["pk"],
        pk_source_columns=["codft"],
        columns=[
            ColumnDef("pk", "VARCHAR"),
            ColumnDef("login_site", "VARCHAR"),
            ColumnDef("codft", "INTEGER"),
            ColumnDef("codrec", "INTEGER"),
            ColumnDef("librec", "VARCHAR"),
            ColumnDef("libred", "VARCHAR"),
            ColumnDef("typrec", "INTEGER"),
            ColumnDef("famrec", "VARCHAR"),
            ColumnDef("sfamrec", "VARCHAR"),
            ColumnDef("fsfcleuniq", "VARCHAR"),
            ColumnDef("codate", "VARCHAR"),
            ColumnDef("codftg4", "VARCHAR"),
            ColumnDef("typlib", "VARCHAR"),
            ColumnDef("datcre", "VARCHAR"),
            ColumnDef("datmaj", "VARCHAR"),
            ColumnDef("dateval", "VARCHAR"),
            ColumnDef("derfab", "VARCHAR"),
            ColumnDef("dersor", "VARCHAR"),
            ColumnDef("nbparts", "INTEGER"),
            ColumnDef("pu", "DOUBLE"),
            ColumnDef("puht", "DOUBLE"),
            ColumnDef("pvht", "DOUBLE"),
            ColumnDef("pvttc", "DOUBLE"),
            ColumnDef("coefpv", "DOUBLE"),
            ColumnDef("conserv", "INTEGER"),
            ColumnDef("delliv", "INTEGER"),
            ColumnDef("image", "INTEGER"),
            ColumnDef("clarec", "INTEGER"),
            ColumnDef("id_frequence", "INTEGER"),
            ColumnDef("id_matos", "INTEGER"),
            ColumnDef("codftfab", "INTEGER"),
            ColumnDef("pcb", "INTEGER"),
            ColumnDef("pcbliv", "INTEGER"),
            ColumnDef("tempcons", "INTEGER"),
            ColumnDef("tconserv_min", "INTEGER"),
            ColumnDef("id_enseignant", "INTEGER"),
            ColumnDef("id_objetft", "INTEGER"),
            ColumnDef("etat", "INTEGER"),
            ColumnDef("statut", "INTEGER"),
            ColumnDef("c0upe", "INTEGER"),
            ColumnDef("typcondtucl", "INTEGER"),
            ColumnDef("lipides", "DOUBLE"),
            ColumnDef("glucides", "DOUBLE"),
            ColumnDef("protides", "DOUBLE"),
            ColumnDef("energie", "DOUBLE"),
            ColumnDef("usart", "VARCHAR"),
            ColumnDef("codtva", "VARCHAR"),
            ColumnDef("tprep", "VARCHAR"),
            ColumnDef("tcuis", "VARCHAR"),
            ColumnDef("trefr", "VARCHAR"),
            ColumnDef("tremi", "VARCHAR"),
            ColumnDef("etapes", "VARCHAR"),
            ColumnDef("saison", "VARCHAR"),
            ColumnDef("libmenu", "VARCHAR"),
            ColumnDef("sel", "BOOLEAN"),
            ColumnDef("reglearr", "BOOLEAN"),
            ColumnDef("porc", "BOOLEAN"),
            ColumnDef("valide", "BOOLEAN"),
            ColumnDef("validedef", "BOOLEAN"),
            ColumnDef("intolerance", "BOOLEAN"),
            ColumnDef("sh", "BOOLEAN"),
            ColumnDef("circuitcourt", "BOOLEAN"),
            ColumnDef("bio", "BOOLEAN"),
            ColumnDef("vegetarien", "BOOLEAN"),
            ColumnDef("maison", "BOOLEAN"),
            ColumnDef("antigaspi", "BOOLEAN"),
            ColumnDef("grammages", "VARCHAR"),
            ColumnDef("typcond", "VARCHAR"),
            ColumnDef("regime", "VARCHAR"),
            ColumnDef("menus", "VARCHAR"),
            ColumnDef("condtucl", "VARCHAR"),
            ColumnDef("allergenes", "VARCHAR"),
            ColumnDef("id_label", "VARCHAR"),
            ColumnDef("poids_ingredient_principal_calcul", "VARCHAR"),
            ColumnDef("poids_ingredient_principal_saisi", "VARCHAR"),
            ColumnDef("descfic_statut", "BIGINT"),
        ],
    ),

    # ── Tables SQL (agrégations — pas de fetch API) ───────────────────────────
    # Ces schémas servent uniquement au DDL (CREATE TABLE) et à la validation.
    # Les jobs de calcul sont séparés (reporting Trino).

    "stat_effect_cred_1": TableSchema(
        partitioning=["login_site"],
        columns=[
            ColumnDef("datej", "DATE"),
            ColumnDef("codss1", "VARCHAR"),
            ColumnDef("codss2", "VARCHAR"),
            ColumnDef("code_site", "BIGINT"),
            ColumnDef("login_site", "VARCHAR"),
            ColumnDef("logingroup", "VARCHAR"),
            ColumnDef("efreel", "DOUBLE"),
            ColumnDef("totcredit", "DOUBLE"),
            ColumnDef("totsortie", "DOUBLE"),
            ColumnDef("nb_vegetarien", "BIGINT"),
            ColumnDef("eff_prev", "DOUBLE"),
            ColumnDef("eff_reel_service", "DOUBLE"),
            ColumnDef("eff_prod", "DOUBLE"),
            ColumnDef("origine", "VARCHAR"),
            ColumnDef("id_animation_1", "BIGINT"),
            ColumnDef("id_animation_2", "BIGINT"),
            ColumnDef("id_animation_3", "BIGINT"),
            ColumnDef("id_animation_4", "BIGINT"),
            ColumnDef("id_animation_5", "BIGINT"),
            ColumnDef("type_menu_1", "BIGINT"),
            ColumnDef("type_menu_2", "BIGINT"),
            ColumnDef("type_menu_3", "BIGINT"),
            ColumnDef("type_menu_4", "BIGINT"),
            ColumnDef("type_menu_5", "BIGINT"),
            ColumnDef("nometabs", "VARCHAR"),
            ColumnDef("ville", "VARCHAR"),
            ColumnDef("id_arrondissement", "BIGINT"),
            ColumnDef("id_canton", "BIGINT"),
            ColumnDef("libss2", "VARCHAR"),
            ColumnDef("libss1", "VARCHAR"),
            ColumnDef("detail_date_import", "TIMESTAMP(6)"),
            ColumnDef("detail_date_modif", "TIMESTAMP(6)"),
            ColumnDef("nb_eleves", "DOUBLE"),
            ColumnDef("nb_commensaux", "DOUBLE"),
        ],
    ),

    "stats_dashboard": TableSchema(
        columns=[
            ColumnDef("annee", "VARCHAR"),
            ColumnDef("login_group", "VARCHAR"),
            ColumnDef("type_produit", "VARCHAR"),
            ColumnDef("local_label", "VARCHAR"),
            ColumnDef("bio_label", "VARCHAR"),
            ColumnDef("egalim_label", "VARCHAR"),
            ColumnDef("montant", "DOUBLE"),
            ColumnDef("montantht", "DOUBLE"),
            ColumnDef("nb_site", "BIGINT"),
        ],
    ),

    "stats_dashboard_effect": TableSchema(
        columns=[
            ColumnDef("logingroup", "VARCHAR"),
            ColumnDef("annee", "VARCHAR"),
            ColumnDef("service", "VARCHAR"),
            ColumnDef("repas_servis", "DOUBLE"),
            ColumnDef("repas_par_jour", "DOUBLE"),
            ColumnDef("nb_sites", "BIGINT"),
            ColumnDef("prix_revient", "DOUBLE"),
            ColumnDef("repas_par_jour2", "DOUBLE"),
        ],
    ),

    "stats_fcj59": TableSchema(
        partitioning=["login_site"],
        columns=[
            ColumnDef("datej", "DATE"),
            ColumnDef("codss1", "VARCHAR"),
            ColumnDef("codss2", "VARCHAR"),
            ColumnDef("code_site", "BIGINT"),
            ColumnDef("login_site", "VARCHAR"),
            ColumnDef("logingroup", "VARCHAR"),
            ColumnDef("efreel", "DOUBLE"),
            ColumnDef("totcredit", "DOUBLE"),
            ColumnDef("totsortie", "DOUBLE"),
            ColumnDef("id_animation_1", "BIGINT"),
            ColumnDef("id_animation_2", "BIGINT"),
            ColumnDef("id_animation_3", "BIGINT"),
            ColumnDef("id_animation_4", "BIGINT"),
            ColumnDef("id_animation_5", "BIGINT"),
            ColumnDef("type_menu_1", "BIGINT"),
            ColumnDef("type_menu_2", "BIGINT"),
            ColumnDef("type_menu_3", "BIGINT"),
            ColumnDef("type_menu_4", "BIGINT"),
            ColumnDef("type_menu_5", "BIGINT"),
            ColumnDef("nb_vegetarien", "BIGINT"),
            ColumnDef("eff_prev", "DOUBLE"),
            ColumnDef("eff_reel_service", "DOUBLE"),
            ColumnDef("eff_prod", "DOUBLE"),
            ColumnDef("origine", "VARCHAR"),
            ColumnDef("date_import", "TIMESTAMP(6)"),
            ColumnDef("date_modif", "TIMESTAMP(6)"),
        ],
    ),

    "stats_fcj59_detail": TableSchema(
        partitioning=["login_site"],
        columns=[
            ColumnDef("datej", "DATE"),
            ColumnDef("codss1", "VARCHAR"),
            ColumnDef("codss2", "VARCHAR"),
            ColumnDef("code_site", "BIGINT"),
            ColumnDef("login_site", "VARCHAR"),
            ColumnDef("logingroup", "VARCHAR"),
            ColumnDef("id_effect", "BIGINT"),
            ColumnDef("codcateg", "VARCHAR"),
            ColumnDef("libcateg", "VARCHAR"),
            ColumnDef("effreel", "DOUBLE"),
            ColumnDef("efftheo", "DOUBLE"),
            ColumnDef("typecateg", "BIGINT"),
            ColumnDef("tarifnet", "DOUBLE"),
            ColumnDef("typfac", "BIGINT"),
            ColumnDef("tarifbrut", "DOUBLE"),
            ColumnDef("origine", "VARCHAR"),
            ColumnDef("date_import", "TIMESTAMP(6)"),
            ColumnDef("date_modif", "TIMESTAMP(6)"),
        ],
    ),

    "stats_liv": TableSchema(
        partitioning=["login_site"],
        columns=[
            ColumnDef("code_site", "BIGINT"),
            ColumnDef("login_site", "VARCHAR"),
            ColumnDef("logingroup", "VARCHAR"),
            ColumnDef("bio", "BIGINT"),
            ColumnDef("clocal", "BIGINT"),
            ColumnDef("label1", "BIGINT"),
            ColumnDef("label2", "BIGINT"),
            ColumnDef("qte", "DOUBLE"),
            ColumnDef("montant", "DOUBLE"),
            ColumnDef("libfou", "VARCHAR"),
            ColumnDef("idfou", "BIGINT"),
            ColumnDef("montantht", "DOUBLE"),
            ColumnDef("codfamfou", "VARCHAR"),
            ColumnDef("date_import", "TIMESTAMP(6)"),
            ColumnDef("date_modif", "TIMESTAMP(6)"),
            ColumnDef("annee", "VARCHAR"),
            ColumnDef("semaine", "VARCHAR"),
            ColumnDef("famille_article", "VARCHAR"),
            ColumnDef("sous_famille_article", "VARCHAR"),
            ColumnDef("lib_famille_article", "VARCHAR"),
            ColumnDef("lib_sous_famille_article", "VARCHAR"),
        ],
    ),

    "stats_liv59": TableSchema(
        partitioning=["login_site"],
        columns=[
            ColumnDef("code_site", "BIGINT"),
            ColumnDef("login_site", "VARCHAR"),
            ColumnDef("logingroup", "VARCHAR"),
            ColumnDef("bio", "BIGINT"),
            ColumnDef("clocal", "BIGINT"),
            ColumnDef("label1", "BIGINT"),
            ColumnDef("label2", "BIGINT"),
            ColumnDef("qte", "DOUBLE"),
            ColumnDef("montant", "DOUBLE"),
            ColumnDef("montantht", "DOUBLE"),
            ColumnDef("date_import", "TIMESTAMP(6)"),
            ColumnDef("date_modif", "TIMESTAMP(6)"),
            ColumnDef("sous_famille_article", "VARCHAR"),
            ColumnDef("annee", "VARCHAR"),
            ColumnDef("semaine", "VARCHAR"),
            ColumnDef("famille_article", "VARCHAR"),
            ColumnDef("lib_famille_article", "VARCHAR"),
            ColumnDef("lib_sous_famille_article", "VARCHAR"),
        ],
    ),

    "stats_liv_annee": TableSchema(
        partitioning=["login_site"],
        columns=[
            ColumnDef("annee", "VARCHAR"),
            ColumnDef("famille_article", "VARCHAR"),
            ColumnDef("sous_famille_article", "VARCHAR"),
            ColumnDef("code_site", "BIGINT"),
            ColumnDef("login_site", "VARCHAR"),
            ColumnDef("logingroup", "VARCHAR"),
            ColumnDef("bio", "BIGINT"),
            ColumnDef("clocal", "BIGINT"),
            ColumnDef("label1", "BIGINT"),
            ColumnDef("idorigine", "BIGINT"),
            ColumnDef("label2", "BIGINT"),
            ColumnDef("qte", "DOUBLE"),
            ColumnDef("montant", "DOUBLE"),
            ColumnDef("libfou", "VARCHAR"),
            ColumnDef("idfou", "BIGINT"),
            ColumnDef("montantht", "DOUBLE"),
            ColumnDef("codfamfou", "VARCHAR"),
            ColumnDef("date_import", "TIMESTAMP(6)"),
            ColumnDef("date_modif", "TIMESTAMP(6)"),
            ColumnDef("lib_sous_famille_article", "VARCHAR"),
            ColumnDef("lib_famille_article", "VARCHAR"),
        ],
    ),

    "stats_liv_mois": TableSchema(
        partitioning=["login_site"],
        columns=[
            ColumnDef("annee", "VARCHAR"),
            ColumnDef("mois", "VARCHAR"),
            ColumnDef("famille_article", "VARCHAR"),
            ColumnDef("sous_famille_article", "VARCHAR"),
            ColumnDef("code_site", "BIGINT"),
            ColumnDef("login_site", "VARCHAR"),
            ColumnDef("logingroup", "VARCHAR"),
            ColumnDef("bio", "BIGINT"),
            ColumnDef("clocal", "BIGINT"),
            ColumnDef("label1", "BIGINT"),
            ColumnDef("idorigine", "BIGINT"),
            ColumnDef("label2", "BIGINT"),
            ColumnDef("qte", "DOUBLE"),
            ColumnDef("montant", "DOUBLE"),
            ColumnDef("libfou", "VARCHAR"),
            ColumnDef("idfou", "BIGINT"),
            ColumnDef("montantht", "DOUBLE"),
            ColumnDef("codfamfou", "VARCHAR"),
            ColumnDef("date_import", "TIMESTAMP(6)"),
            ColumnDef("date_modif", "TIMESTAMP(6)"),
            ColumnDef("lib_famille_article", "VARCHAR"),
            ColumnDef("lib_sous_famille_article", "VARCHAR"),
        ],
    ),

    "stats_liv_egalim_jour": TableSchema(
        partitioning=["login_site"],
        columns=[
            ColumnDef("jour", "DATE"),
            ColumnDef("code_site", "BIGINT"),
            ColumnDef("login_site", "VARCHAR"),
            ColumnDef("famille_article", "VARCHAR"),
            ColumnDef("sous_famille_article", "VARCHAR"),
            ColumnDef("lib_famille_article", "VARCHAR"),
            ColumnDef("lib_sous_famille_article", "VARCHAR"),
            ColumnDef("montant", "DOUBLE"),
            ColumnDef("montantht", "DOUBLE"),
            ColumnDef("qte", "DOUBLE"),
            ColumnDef("local_valeur", "DOUBLE"),
            ColumnDef("bio_valeur", "DOUBLE"),
            ColumnDef("egalim_valeur", "DOUBLE"),
            ColumnDef("bio_local_valeur", "DOUBLE"),
            ColumnDef("local_pct", "DOUBLE"),
            ColumnDef("bio_pct", "DOUBLE"),
            ColumnDef("egalim_pct", "DOUBLE"),
            ColumnDef("bio_local_pct", "DOUBLE"),
            ColumnDef("date_import", "TIMESTAMP(6)"),
            ColumnDef("date_modif", "TIMESTAMP(6)"),
        ],
    ),

    "stats_recap_site": TableSchema(
        partitioning=["login_site"],
        columns=[
            ColumnDef("code_site", "BIGINT"),
            ColumnDef("login_site", "VARCHAR"),
            ColumnDef("logingroup", "VARCHAR"),
            ColumnDef("datestat", "DATE"),
            ColumnDef("neff", "DOUBLE"),
            ColumnDef("vtotent", "DOUBLE"),
            ColumnDef("vtotsor", "DOUBLE"),
            ColumnDef("rpr", "DOUBLE"),
            ColumnDef("nbjoursaisie", "BIGINT"),
            ColumnDef("neffserv_1", "DOUBLE"),
            ColumnDef("neffserv_2", "DOUBLE"),
            ColumnDef("neffserv_3", "DOUBLE"),
            ColumnDef("neffserv_4", "DOUBLE"),
            ColumnDef("neffserv_5", "DOUBLE"),
            ColumnDef("vtotsorserv_1", "DOUBLE"),
            ColumnDef("vtotsorserv_2", "DOUBLE"),
            ColumnDef("vtotsorserv_3", "DOUBLE"),
            ColumnDef("vtotsorserv_4", "DOUBLE"),
            ColumnDef("vtotsorserv_5", "DOUBLE"),
        ],
    ),
}

# Tables qui ont des métadonnées de fetch (les autres sont SQL reporting)
WEBGEREST_FETCH_TABLES = {
    k for k, v in WEBGEREST_SCHEMAS.items() if v.primary_keys is not None
}
