"""
Schémas V2 des tables Webgerest — architecture démultipliée.

Contrairement à la V1 (une table par type partitionnée sur login_site), la V2 crée
une table physique distincte par login_group ou login_site selon le statut dans descfic :

    {server_prefix}login                    → table unique par serveur
    {server_prefix}{group}_descfic          → une par login_group
    {server_prefix}{group}_{table}          → données statut=1 (fetch par groupe)
    {server_prefix}{site}_{table}           → données statut=2 (fetch par site)

Différences avec V1 :
- Pas de `partitioning` (la table elle-même est la partition)
- Pas de colonne `pk` synthétique → primary_keys = colonnes métier directes
- Pas de colonne `login_site` / `login_group` dans les données (dans le nom de table)
- Pas de colonne `descfic_statut` (inutile par table)
- Tables SQL (agrégations reporting) : exclues de ce dict — restent en V1

`transform_generic` fonctionne sans modification : les colonnes non déclarées dans le
schéma (login_site injecté, pk inexistant) sont simplement ignorées à la sélection finale.
"""

from data_process.process.ddl import ColumnDef, TableSchema

WEBGEREST_V2_SCHEMAS: dict[str, TableSchema] = {

    # ── Tables spéciales (jobs dédiés) ───────────────────────────────────────

    "login": TableSchema(
        primary_keys=["login"],
        columns=[
            ColumnDef("login", "VARCHAR"),
            ColumnDef("logingroupe", "VARCHAR"),
            ColumnDef("nometabs", "VARCHAR"),
            ColumnDef("ville", "VARCHAR"),
            ColumnDef("datactif", "DATE"),
            ColumnDef("datinactif", "DATE"),
            ColumnDef("fictif", "BOOLEAN"),
            ColumnDef("statut", "BIGINT"),
            ColumnDef("code_site", "BIGINT"),
            ColumnDef("profil", "BIGINT"),
            ColumnDef("secteur", "BIGINT"),
            ColumnDef("cheminbdd", "VARCHAR"),
            ColumnDef("gestionnaire", "BOOLEAN"),
            ColumnDef("souslogingroupe", "VARCHAR"),
            ColumnDef("id_arrondissement", "BIGINT"),
            ColumnDef("id_canton", "BIGINT"),
            ColumnDef("code_postal", "BIGINT"),
        ],
        date_formats={"datactif": "%Y%m%d", "datinactif": "%Y%m%d"},
    ),

    "descfic": TableSchema(
        primary_keys=["nomfic"],
        site_column="login_group",
        columns=[
            ColumnDef("nomfic", "VARCHAR"),
            ColumnDef("statut", "BIGINT"),
            ColumnDef("description", "VARCHAR"),
        ],
    ),

    # ── Tables de référence (full reload par site/groupe) ────────────────────

    "article": TableSchema(
        primary_keys=["arcleunik"],
        pk_source_columns=[],
        column_updates="datmod",
        column_renames={"usart_vers_ufa": "usart_vers_ufam"},
        date_formats={"dcreart": "%Y%m%d"},
        columns=[
            ColumnDef("arcleunik", "BIGINT"),
            ColumnDef("codart", "BIGINT"),
            ColumnDef("libart", "VARCHAR"),
            ColumnDef("codfamart", "VARCHAR"),
            ColumnDef("sfaart", "VARCHAR"),
            ColumnDef("usart", "VARCHAR"),
            ColumnDef("dpaart", "DOUBLE"),
            ColumnDef("pmpart", "DOUBLE"),
            ColumnDef("qtethe", "DOUBLE"),
            ColumnDef("qtecom", "DOUBLE"),
            ColumnDef("dcreart", "DATE"),
            ColumnDef("slqte", "DOUBLE"),
            ColumnDef("codstk", "VARCHAR"),
            ColumnDef("codtva", "VARCHAR"),
            ColumnDef("conditionne", "BOOLEAN"),
            ColumnDef("suivi", "BOOLEAN"),
            ColumnDef("percde", "BIGINT"),
            ColumnDef("delai", "BIGINT"),
            ColumnDef("reglecalc", "BIGINT"),
            ColumnDef("catol", "VARCHAR"),
            ColumnDef("pdsbrut", "DOUBLE"),
            ColumnDef("glucides", "DOUBLE"),
            ColumnDef("lipides", "DOUBLE"),
            ColumnDef("protides", "DOUBLE"),
            ColumnDef("energie", "DOUBLE"),
            ColumnDef("qtecomus", "DOUBLE"),
            ColumnDef("reglearr", "BIGINT"),
            ColumnDef("uniteft", "VARCHAR"),
            ColumnDef("seuilmaxi", "DOUBLE"),
            ColumnDef("nature", "BIGINT"),
            ColumnDef("pdsvol", "DOUBLE"),
            ColumnDef("statut", "BIGINT"),
            ColumnDef("datmod", "TIMESTAMP(6)"),
            ColumnDef("id_marche", "BIGINT"),
            ColumnDef("id_lots", "BIGINT"),
            ColumnDef("bio", "BOOLEAN"),
            ColumnDef("designation_externe", "VARCHAR"),
            ColumnDef("allergenes", "VARCHAR"),
            ColumnDef("codarticle", "VARCHAR"),
            ColumnDef("usart_vers_ufam", "DOUBLE"),
            ColumnDef("logincrea", "VARCHAR"),
        ],
    ),

    "categ": TableSchema(
        primary_keys=["codcat"],
        pk_source_columns=[],
        columns=[
            ColumnDef("codimp", "BIGINT"),
            ColumnDef("famcat", "BIGINT"),
            ColumnDef("libcat", "VARCHAR"),
            ColumnDef("nbjsem", "BIGINT"),
            ColumnDef("noncompte", "BOOLEAN"),
            ColumnDef("onilait", "BOOLEAN"),
            ColumnDef("ordre", "BIGINT"),
            ColumnDef("regime", "BIGINT"),
            ColumnDef("service", "VARCHAR"),
            ColumnDef("statut", "BIGINT"),
            ColumnDef("typfac", "BIGINT"),
            ColumnDef("codcat", "VARCHAR"),
        ],
    ),

    "detail_article": TableSchema(
        primary_keys=["id_detailarticle"],
        pk_source_columns=[],
        api_table_name="detailarticle",
        columns=[
            ColumnDef("id_detailarticle", "BIGINT"),
            ColumnDef("arcleunik", "BIGINT"),
            ColumnDef("circuit_court", "BOOLEAN"),
            ColumnDef("saison_deb", "BIGINT"),
            ColumnDef("saison_fin", "BIGINT"),
            ColumnDef("id_label", "BIGINT"),
            ColumnDef("id_origine", "BIGINT"),
            ColumnDef("codart", "BIGINT"),
            ColumnDef("zinc", "DOUBLE"),
            ColumnDef("fer", "DOUBLE"),
            ColumnDef("iode", "DOUBLE"),
            ColumnDef("selenium", "DOUBLE"),
            ColumnDef("dha", "DOUBLE"),
            ColumnDef("epa", "DOUBLE"),
            ColumnDef("vit_b3", "DOUBLE"),
            ColumnDef("vit_b6", "DOUBLE"),
            ColumnDef("vit_b12", "DOUBLE"),
            ColumnDef("vit_d", "DOUBLE"),
            ColumnDef("id_calories", "BIGINT"),
            ColumnDef("calcium", "DOUBLE"),
            ColumnDef("sodium", "DOUBLE"),
            ColumnDef("sucre", "DOUBLE"),
            ColumnDef("glucose", "DOUBLE"),
            ColumnDef("amidon", "DOUBLE"),
            ColumnDef("fibre", "DOUBLE"),
            ColumnDef("vit_c", "DOUBLE"),
            ColumnDef("magnesium", "DOUBLE"),
            ColumnDef("vit_e", "DOUBLE"),
            ColumnDef("vit_b2", "DOUBLE"),
            ColumnDef("cuivre", "DOUBLE"),
            ColumnDef("vit_a_retinol", "DOUBLE"),
            ColumnDef("vit_k", "DOUBLE"),
            ColumnDef("vit_b9", "DOUBLE"),
            ColumnDef("potassium", "DOUBLE"),
            ColumnDef("phosphore", "DOUBLE"),
            ColumnDef("vit_b1", "DOUBLE"),
            ColumnDef("vit_a_beta_caro", "DOUBLE"),
            ColumnDef("vit_b5", "DOUBLE"),
            ColumnDef("favori", "BOOLEAN"),
            ColumnDef("jamais_local", "BOOLEAN"),
            ColumnDef("acide_gras_sature", "DOUBLE"),
        ],
    ),

    "famart": TableSchema(
        primary_keys=["codfamart"],
        pk_source_columns=[],
        columns=[
            ColumnDef("codfamart", "VARCHAR"),
            ColumnDef("libfamart", "VARCHAR"),
            ColumnDef("typart", "BIGINT"),
            ColumnDef("cptfam_1", "VARCHAR"),
            ColumnDef("cptfam_2", "VARCHAR"),
            ColumnDef("cptfam_3", "VARCHAR"),
            ColumnDef("cptfam_4", "VARCHAR"),
            ColumnDef("cptfam_5", "VARCHAR"),
            ColumnDef("cptfam_6", "VARCHAR"),
            ColumnDef("cptfam_7", "VARCHAR"),
            ColumnDef("cptfam_8", "VARCHAR"),
            ColumnDef("cptfam_9", "VARCHAR"),
            ColumnDef("cptfam_10", "VARCHAR"),
            ColumnDef("type", "BIGINT"),
            ColumnDef("statut", "BOOLEAN"),
            ColumnDef("ordre", "BIGINT"),
            ColumnDef("jamais_local", "BOOLEAN"),
        ],
    ),

    "fourn": TableSchema(
        site_column="login_site",
        primary_keys=["f_ocleunik"],
        pk_source_columns=[],
        column_renames={"label": "id_label"},
        columns=[
            ColumnDef("f_ocleunik", "BIGINT"),
            ColumnDef("codfou", "VARCHAR"),
            ColumnDef("libfou", "VARCHAR"),
            ColumnDef("codfamfou", "VARCHAR"),
            ColumnDef("cpfou", "VARCHAR"),
            ColumnDef("minfac", "DOUBLE"),
            ColumnDef("jours", "VARCHAR"),
            ColumnDef("delai", "BIGINT"),
            ColumnDef("numcli", "VARCHAR"),
            ColumnDef("percde", "BIGINT"),
            ColumnDef("statut", "BIGINT"),
            ColumnDef("login", "VARCHAR"),
            ColumnDef("circuit_court", "BOOLEAN"),
            ColumnDef("num_agrement", "VARCHAR"),
            ColumnDef("bio", "BOOLEAN"),
            ColumnDef("no_engagement", "VARCHAR"),
            ColumnDef("id_fourn_ext", "BIGINT"),
            ColumnDef("id_origine", "BIGINT"),
            ColumnDef("id_label", "BIGINT"),
            ColumnDef("tags", "VARCHAR"),
            ColumnDef("agrimer_fl", "BOOLEAN"),
            ColumnDef("agrimer_lait", "BOOLEAN"),
            ColumnDef("circuit_court_strict", "BOOLEAN"),
        ],
    ),

    "label": TableSchema(
        primary_keys=["id_label"],
        pk_source_columns=[],
        columns=[
            ColumnDef("code", "BIGINT"),
            ColumnDef("id_label", "BIGINT"),
            ColumnDef("label", "VARCHAR"),
            ColumnDef("egalim", "BOOLEAN"),
        ],
    ),

    "ntarif": TableSchema(
        primary_keys=["id_ntarif"],
        pk_source_columns=[],
        columns=[
            ColumnDef("id_ntarif", "BIGINT"),
            ColumnDef("exercice", "VARCHAR"),
            ColumnDef("codcli", "BIGINT"),
            ColumnDef("codcat", "VARCHAR"),
            ColumnDef("typfac", "BIGINT"),
            ColumnDef("codimp", "BIGINT"),
            ColumnDef("creditbrut", "VARCHAR"),
            ColumnDef("creditnet", "VARCHAR"),
            ColumnDef("forfaitan", "DOUBLE"),
            ColumnDef("forfaittrim", "VARCHAR"),
            ColumnDef("coeftrim", "VARCHAR"),
            ColumnDef("nbjan", "BIGINT"),
            ColumnDef("nbjtrim", "VARCHAR"),
            ColumnDef("nbjsem", "BIGINT"),
            ColumnDef("coefserv", "VARCHAR"),
            ColumnDef("statut", "BIGINT"),
            ColumnDef("prestation", "VARCHAR"),
        ],
    ),

    "sfaart": TableSchema(
        primary_keys=["codfamart", "sfaart"],
        pk_source_columns=[],
        columns=[
            ColumnDef("codfamart", "VARCHAR"),
            ColumnDef("sfaart", "VARCHAR"),
            ColumnDef("libsfaart", "VARCHAR"),
            ColumnDef("typart", "BIGINT"),
            ColumnDef("unite", "VARCHAR"),
            ColumnDef("type", "BIGINT"),
            ColumnDef("statut", "BOOLEAN"),
            ColumnDef("ordre", "BIGINT"),
            ColumnDef("jamais_local", "BOOLEAN"),
        ],
    ),

    "trimestre": TableSchema(
        primary_keys=["notrim", "exercice"],
        pk_source_columns=[],
        columns=[
            ColumnDef("exercice", "VARCHAR"),
            ColumnDef("datdeb", "DATE"),
            ColumnDef("datfin", "DATE"),
            ColumnDef("notrim", "BIGINT"),
            ColumnDef("nbjtrim", "BIGINT"),
        ],
    ),

    "typss1": TableSchema(
        primary_keys=["codss1"],
        pk_source_columns=[],
        columns=[
            ColumnDef("libss1", "VARCHAR"),
            ColumnDef("onilait", "BOOLEAN"),
            ColumnDef("codcpt", "VARCHAR"),
            ColumnDef("boolsh", "BOOLEAN"),
            ColumnDef("id_catpresta", "BIGINT"),
            ColumnDef("no_variante", "BIGINT"),
            ColumnDef("ordre", "BIGINT"),
            ColumnDef("codss1", "VARCHAR"),
        ],
    ),

    "typss2": TableSchema(
        primary_keys=["codss2"],
        pk_source_columns=[],
        columns=[
            ColumnDef("libss2", "VARCHAR"),
            ColumnDef("bool_supprimable", "BOOLEAN"),
            ColumnDef("statut", "BIGINT"),
            ColumnDef("codss2", "VARCHAR"),
        ],
    ),

    # ── Tables opérationnelles (upsert incrémental) ───────────────────────────

    "effect": TableSchema(
        primary_keys=["id_effect"],
        pk_source_columns=[],
        column_updates="efdate",
        column_renames={"efcleunik": "id_effect"},
        columns=[
            ColumnDef("efdate", "DATE"),
            ColumnDef("id_effect", "BIGINT"),
            ColumnDef("eftheo", "BIGINT"),
            ColumnDef("efreel", "BIGINT"),
            ColumnDef("efprev", "BIGINT"),
            ColumnDef("credit", "DOUBLE"),
            ColumnDef("codcat", "VARCHAR"),
            ColumnDef("typfac", "BIGINT"),
            ColumnDef("codcli", "BIGINT"),
            ColumnDef("effautre", "BIGINT"),
            ColumnDef("creditbrut", "DOUBLE"),
            ColumnDef("origine", "VARCHAR"),
            ColumnDef("date_import", "DATE"),
            ColumnDef("date_modif", "DATE"),
            ColumnDef("codss1", "VARCHAR"),
            ColumnDef("codss2", "VARCHAR"),
        ],
    ),

    "feuille": TableSchema(
        primary_keys=["fecleunik"],
        pk_source_columns=[],
        columns=[
            ColumnDef("fecleunik", "BIGINT"),
            ColumnDef("efdate", "DATE"),
            ColumnDef("codss1", "VARCHAR"),
            ColumnDef("menu", "VARCHAR"),
            ColumnDef("commentaire", "VARCHAR"),
            ColumnDef("codss2", "VARCHAR"),
            ColumnDef("cle_jps", "VARCHAR"),
            ColumnDef("nb_vegetarien", "BIGINT"),
            ColumnDef("type_menu", "VARCHAR"),
            ColumnDef("id_animation", "VARCHAR"),
        ],
    ),

    "gaspi_saisie_gen": TableSchema(
        primary_keys=["id_gaspi_saisie_gen"],
        pk_source_columns=[],
        column_updates="datej",
        columns=[
            ColumnDef("id_gaspi_saisie_gen", "BIGINT"),
            ColumnDef("datej", "DATE"),
            ColumnDef("codss1", "VARCHAR"),
            ColumnDef("codss2", "VARCHAR"),
            ColumnDef("qte_gen", "DOUBLE"),
            ColumnDef("cle_jps", "VARCHAR"),
            ColumnDef("eff_prev", "BIGINT"),
            ColumnDef("pas_de_tri", "BOOLEAN"),
            ColumnDef("commentaire", "VARCHAR"),
            ColumnDef("eff_prod", "BIGINT"),
            ColumnDef("eff_reel_service", "BIGINT"),
        ],
    ),

    "mvtart": TableSchema(
        primary_keys=["mvcleunik"],
        pk_source_columns=[],
        column_updates="dtemvt",
        columns=[
            ColumnDef("mvcleunik", "BIGINT"),
            ColumnDef("dtemvt", "TIMESTAMP(6)"),
            ColumnDef("typmvt", "BIGINT"),
            ColumnDef("stypmvt", "VARCHAR"),
            ColumnDef("nobon", "VARCHAR"),
            ColumnDef("f_ocleunik", "BIGINT"),
            ColumnDef("arcleunik", "BIGINT"),
            ColumnDef("c0_cleunik", "BIGINT"),
            ColumnDef("qteart", "DOUBLE"),
            ColumnDef("codun", "VARCHAR"),
            ColumnDef("prixht", "DOUBLE"),
            ColumnDef("poremise", "DOUBLE"),
            ColumnDef("taux_tva", "DOUBLE"),
            ColumnDef("pmpart", "DOUBLE"),
            ColumnDef("uatous", "DOUBLE"),
            ColumnDef("e0_cleunik", "BIGINT"),
            ColumnDef("etat", "BIGINT"),
            ColumnDef("trv", "VARCHAR"),
            ColumnDef("numlot", "VARCHAR"),
            ColumnDef("dlc", "DATE"),
            ColumnDef("libart", "VARCHAR"),
            ColumnDef("usart", "VARCHAR"),
            ColumnDef("qteusart", "DOUBLE"),
            ColumnDef("valide", "BOOLEAN"),
            ColumnDef("pcb", "DOUBLE"),
            ColumnDef("totht", "DOUBLE"),
            ColumnDef("totttc", "DOUBLE"),
            ColumnDef("pmpart_ttc", "DOUBLE"),
            ColumnDef("qtefac", "DOUBLE"),
            ColumnDef("pufac", "DOUBLE"),
            ColumnDef("codate", "VARCHAR"),
            ColumnDef("e0_codart", "VARCHAR"),
            ColumnDef("e0_libart", "VARCHAR"),
            ColumnDef("uatoufac", "DOUBLE"),
            ColumnDef("ufac", "VARCHAR"),
            ColumnDef("qtef", "DOUBLE"),
            ColumnDef("puf", "DOUBLE"),
            ColumnDef("stockavant", "DOUBLE"),
            ColumnDef("pmp_avt", "DOUBLE"),
            ColumnDef("dteimp", "DATE"),
            ColumnDef("id_article_lot", "BIGINT"),
            ColumnDef("reference", "VARCHAR"),
            ColumnDef("circuit_court", "BOOLEAN"),
            ColumnDef("id_origine", "BIGINT"),
            ColumnDef("id_label", "BIGINT"),
            ColumnDef("echantillon", "BOOLEAN"),
            ColumnDef("commentaire", "VARCHAR"),
            ColumnDef("bio", "BOOLEAN"),
            ColumnDef("chemin_pj", "VARCHAR"),
            ColumnDef("statut_dlc", "BOOLEAN"),
            ColumnDef("codss1", "VARCHAR"),
            ColumnDef("codss2", "VARCHAR"),
        ],
    ),

    "mvtart_det": TableSchema(
        primary_keys=["id_mvtart_det"],
        pk_source_columns=[],
        columns=[
            ColumnDef("id_mvtart_det", "BIGINT"),
            ColumnDef("mvcleunik", "BIGINT"),
            ColumnDef("modif_local", "BOOLEAN"),
            ColumnDef("modif_bio", "BOOLEAN"),
            ColumnDef("modif_label1", "BOOLEAN"),
            ColumnDef("modif_origine", "BOOLEAN"),
        ],
    ),

    "plandis": TableSchema(
        primary_keys=["plcleunik"],
        pk_source_columns=[],
        column_updates="datdis",
        code_site_from_api=True,
        date_formats={"datdis": "%Y%m%d"},
        columns=[
            ColumnDef("plcleunik", "INTEGER"),
            ColumnDef("an", "VARCHAR"),
            ColumnDef("semaine", "VARCHAR"),
            ColumnDef("jour", "VARCHAR"),
            ColumnDef("service", "VARCHAR"),
            ColumnDef("datdis", "DATE"),
            ColumnDef("effectif", "INTEGER"),
            ColumnDef("prestation", "VARCHAR"),
            ColumnDef("code_site", "INTEGER"),
        ],
    ),

    "detpland": TableSchema(
        primary_keys=["d1_cleunik"],
        pk_source_columns=[],
        column_updates="datfab",
        columns=[
            ColumnDef("d1_cleunik", "BIGINT"),
            ColumnDef("typrec", "VARCHAR"),
            ColumnDef("ordre", "VARCHAR"),
            ColumnDef("codrec", "BIGINT"),
            ColumnDef("plcleunik", "BIGINT"),
            ColumnDef("datfab", "DATE"),
            ColumnDef("datbes", "DATE"),
            ColumnDef("codft", "BIGINT"),
            ColumnDef("typord", "VARCHAR"),
            ColumnDef("recleuniq", "VARCHAR"),
            ColumnDef("id_mvtpre", "BIGINT"),
            ColumnDef("puht", "DOUBLE"),
            ColumnDef("puttc", "DOUBLE"),
            ColumnDef("typpart", "BIGINT"),
            ColumnDef("valsor", "BOOLEAN"),
            ColumnDef("options", "BOOLEAN"),
            ColumnDef("potage", "BOOLEAN"),
            ColumnDef("equillibre", "BOOLEAN"),
            ColumnDef("horsgamme", "BOOLEAN"),
            ColumnDef("intolerance", "BOOLEAN"),
            ColumnDef("no_variante", "BIGINT"),
            ColumnDef("recleunik_variante", "VARCHAR"),
            ColumnDef("qtefab", "VARCHAR"),
            ColumnDef("menus", "VARCHAR"),
            ColumnDef("qtemodif", "VARCHAR"),
            ColumnDef("qteprev", "VARCHAR"),
            ColumnDef("qtefabr1", "VARCHAR"),
            ColumnDef("qtefabr2", "VARCHAR"),
            ColumnDef("qtefabr3", "VARCHAR"),
            ColumnDef("qtemodifr1", "VARCHAR"),
            ColumnDef("qtemodifr2", "VARCHAR"),
            ColumnDef("qtemodifr3", "VARCHAR"),
            ColumnDef("taux_prise", "DOUBLE"),
        ],
    ),

    "fitech": TableSchema(
        primary_keys=["codft"],
        pk_source_columns=[],
        columns=[
            ColumnDef("codft", "INTEGER"),
            ColumnDef("codrec", "INTEGER"),
            ColumnDef("librec", "VARCHAR"),
            ColumnDef("libred", "VARCHAR"),
            ColumnDef("typrec", "INTEGER"),
            ColumnDef("famrec", "VARCHAR"),
            ColumnDef("sfamrec", "VARCHAR"),
            ColumnDef("fsfcleuniq", "VARCHAR"),
            ColumnDef("codate", "VARCHAR"),
            ColumnDef("codftg4", "VARCHAR"),
            ColumnDef("typlib", "VARCHAR"),
            ColumnDef("datcre", "VARCHAR"),
            ColumnDef("datmaj", "VARCHAR"),
            ColumnDef("dateval", "VARCHAR"),
            ColumnDef("derfab", "VARCHAR"),
            ColumnDef("dersor", "VARCHAR"),
            ColumnDef("nbparts", "INTEGER"),
            ColumnDef("pu", "DOUBLE"),
            ColumnDef("puht", "DOUBLE"),
            ColumnDef("pvht", "DOUBLE"),
            ColumnDef("pvttc", "DOUBLE"),
            ColumnDef("coefpv", "DOUBLE"),
            ColumnDef("conserv", "INTEGER"),
            ColumnDef("delliv", "INTEGER"),
            ColumnDef("image", "INTEGER"),
            ColumnDef("clarec", "INTEGER"),
            ColumnDef("id_frequence", "INTEGER"),
            ColumnDef("id_matos", "INTEGER"),
            ColumnDef("codftfab", "INTEGER"),
            ColumnDef("pcb", "INTEGER"),
            ColumnDef("pcbliv", "INTEGER"),
            ColumnDef("tempcons", "INTEGER"),
            ColumnDef("tconserv_min", "INTEGER"),
            ColumnDef("id_enseignant", "INTEGER"),
            ColumnDef("id_objetft", "INTEGER"),
            ColumnDef("etat", "INTEGER"),
            ColumnDef("statut", "INTEGER"),
            ColumnDef("c0upe", "INTEGER"),
            ColumnDef("typcondtucl", "INTEGER"),
            ColumnDef("lipides", "DOUBLE"),
            ColumnDef("glucides", "DOUBLE"),
            ColumnDef("protides", "DOUBLE"),
            ColumnDef("energie", "DOUBLE"),
            ColumnDef("usart", "VARCHAR"),
            ColumnDef("codtva", "VARCHAR"),
            ColumnDef("tprep", "VARCHAR"),
            ColumnDef("tcuis", "VARCHAR"),
            ColumnDef("trefr", "VARCHAR"),
            ColumnDef("tremi", "VARCHAR"),
            ColumnDef("etapes", "VARCHAR"),
            ColumnDef("saison", "VARCHAR"),
            ColumnDef("libmenu", "VARCHAR"),
            ColumnDef("sel", "BOOLEAN"),
            ColumnDef("reglearr", "BOOLEAN"),
            ColumnDef("porc", "BOOLEAN"),
            ColumnDef("valide", "BOOLEAN"),
            ColumnDef("validedef", "BOOLEAN"),
            ColumnDef("intolerance", "BOOLEAN"),
            ColumnDef("sh", "BOOLEAN"),
            ColumnDef("circuitcourt", "BOOLEAN"),
            ColumnDef("bio", "BOOLEAN"),
            ColumnDef("vegetarien", "BOOLEAN"),
            ColumnDef("maison", "BOOLEAN"),
            ColumnDef("antigaspi", "BOOLEAN"),
            ColumnDef("grammages", "VARCHAR"),
            ColumnDef("typcond", "VARCHAR"),
            ColumnDef("regime", "VARCHAR"),
            ColumnDef("menus", "VARCHAR"),
            ColumnDef("condtucl", "VARCHAR"),
            ColumnDef("allergenes", "VARCHAR"),
            ColumnDef("id_label", "VARCHAR"),
            ColumnDef("poids_ingredient_principal_calcul", "VARCHAR"),
            ColumnDef("poids_ingredient_principal_saisi", "VARCHAR"),
        ],
    ),
}

# Tables qui ont des métadonnées de fetch (les autres sont SQL reporting, exclues de V2)
WEBGEREST_V2_FETCH_TABLES = {
    k for k, v in WEBGEREST_V2_SCHEMAS.items() if v.primary_keys is not None
}
