"""Schémas des 17 tables Webresto."""

from data_process.process.ddl import ColumnDef, TableSchema

WEBRESTO_SCHEMAS: dict[str, TableSchema] = {
    "passage": TableSchema([
        ColumnDef("id_passage", "DOUBLE"),
        ColumnDef("id_organization", "DOUBLE"),
        ColumnDef("id_user", "DOUBLE"),
        ColumnDef("id_service", "DOUBLE"),
        ColumnDef("date", "TIMESTAMP(6)"),
        ColumnDef("id_subgroup", "DOUBLE"),
        ColumnDef("created_at", "TIMESTAMP(6)"),
        ColumnDef("updated_at", "TIMESTAMP(6)"),
        ColumnDef("id_tranche", "BIGINT"),
    ]),
    "passage_partner": TableSchema([
        ColumnDef("id_partner", "DOUBLE"),
        ColumnDef("nb_passages", "DOUBLE"),
        ColumnDef("tranche", "DOUBLE"),
        ColumnDef("id_organization", "DOUBLE"),
        ColumnDef("date", "TIMESTAMP(6)"),
        ColumnDef("subgroup", "VARCHAR"),
        ColumnDef("service", "DOUBLE"),
    ]),
    "subgroup_mapping": TableSchema([
        ColumnDef("id_subgroupmaping", "DOUBLE"),
        ColumnDef("subgroup", "VARCHAR"),
        ColumnDef("id_subgroup", "DOUBLE"),
    ]),
    "booking": TableSchema([
        ColumnDef("id_booking", "BIGINT"),
        ColumnDef("id_organization", "BIGINT"),
        ColumnDef("id_user", "BIGINT"),
        ColumnDef("id_service", "BIGINT"),
        ColumnDef("created_at", "TIMESTAMP(6)"),
        ColumnDef("updated_at", "TIMESTAMP(6)"),
        ColumnDef("origin", "VARCHAR"),
        ColumnDef("date", "TIMESTAMP(6)"),
    ]),
    "organization": TableSchema([
        ColumnDef("id_organization", "DOUBLE"),
        ColumnDef("rne", "VARCHAR"),
        ColumnDef("name", "VARCHAR"),
        ColumnDef("city", "VARCHAR"),
        ColumnDef("type", "VARCHAR"),
        ColumnDef("department", "VARCHAR"),
        ColumnDef("academy", "VARCHAR"),
        ColumnDef("access_software", "VARCHAR"),
        ColumnDef("ips", "DOUBLE"),
        ColumnDef("vague", "DOUBLE"),
    ]),
    "service": TableSchema([
        ColumnDef("id_organization", "DOUBLE"),
        ColumnDef("id_service", "DOUBLE"),
        ColumnDef("label", "VARCHAR"),
    ]),
    "subgroup": TableSchema([
        ColumnDef("id_subgroup", "DOUBLE"),
        ColumnDef("label", "VARCHAR"),
        ColumnDef("id_group", "DOUBLE"),
        ColumnDef("acronym", "VARCHAR"),
        ColumnDef("facturation_type", "VARCHAR"),
        ColumnDef("updated_at", "TIMESTAMP(6)"),
        ColumnDef("created_at", "TIMESTAMP(6)"),
    ]),
    "group": TableSchema([
        ColumnDef("id_group", "DOUBLE"),
        ColumnDef("label", "VARCHAR"),
        ColumnDef("acronym", "VARCHAR"),
        ColumnDef("id_organization", "DOUBLE"),
    ]),
    "tranche": TableSchema([
        ColumnDef("id_tranche", "BIGINT"),
        ColumnDef("label", "VARCHAR"),
        ColumnDef("indice", "BIGINT"),
        ColumnDef("id_organization", "DOUBLE"),
        ColumnDef("quotient", "DOUBLE"),
    ]),
    "organization_enrollment": TableSchema([
        ColumnDef("enrollment_id", "BIGINT"),
        ColumnDef("organization_id", "BIGINT"),
        ColumnDef("school_year_id", "BIGINT"),
        ColumnDef("total_enrollment", "BIGINT"),
        ColumnDef("intern_count", "BIGINT"),
        ColumnDef("social_tarif_beneficiaries", "BIGINT"),
    ]),
    "school_year": TableSchema([
        ColumnDef("school_year_id", "BIGINT"),
        ColumnDef("label", "VARCHAR"),
        ColumnDef("start_date", "DATE"),
        ColumnDef("end_date", "DATE"),
    ]),
    "history": TableSchema([
        ColumnDef("id_reg_history", "DOUBLE"),
        ColumnDef("registration_id", "DOUBLE"),
        ColumnDef("event", "VARCHAR"),
        ColumnDef("updated_at", "TIMESTAMP(6)"),
        ColumnDef("created_at", "TIMESTAMP(6)"),
    ]),
    "registration": TableSchema([
        ColumnDef("id", "DOUBLE"),
        ColumnDef("status", "VARCHAR"),
        ColumnDef("id_session", "DOUBLE"),
        ColumnDef("id_user", "DOUBLE"),
        ColumnDef("id_school_year", "BIGINT"),
        ColumnDef("choice_bank_detail", "VARCHAR"),
        ColumnDef("tranche_id", "BIGINT"),
        ColumnDef("subgroup_id", "DOUBLE"),
        ColumnDef("created_at", "TIMESTAMP(6)"),
        ColumnDef("updated_at", "TIMESTAMP(6)"),
    ]),
    "session": TableSchema([
        ColumnDef("id", "DOUBLE"),
        ColumnDef("id_organization", "DOUBLE"),
        ColumnDef("id_vague", "DOUBLE"),
        ColumnDef("name", "VARCHAR"),
    ]),
    "vague": TableSchema([
        ColumnDef("id_vague", "DOUBLE"),
        ColumnDef("name", "VARCHAR"),
        ColumnDef("start_date", "DATE"),
        ColumnDef("end_date", "DATE"),
        ColumnDef("id_school_year", "BIGINT"),
    ]),
    "bankdetail": TableSchema([
        ColumnDef("bank_detail_id", "DOUBLE"),
        ColumnDef("choice_bank_details", "VARCHAR"),
        ColumnDef("id_user", "DOUBLE"),
        ColumnDef("id_tranche", "DOUBLE"),
        ColumnDef("created_at", "TIMESTAMP(6)"),
        ColumnDef("updated_at", "TIMESTAMP(6)"),
    ]),
    "user": TableSchema([
        ColumnDef("id_user", "DOUBLE"),
        ColumnDef("id_subgroup", "DOUBLE"),
        ColumnDef("id_organization", "DOUBLE"),
        ColumnDef("first_name", "VARCHAR"),
        ColumnDef("last_name", "VARCHAR"),
        ColumnDef("date_birth", "DATE"),
        ColumnDef("updated_at", "TIMESTAMP(6)"),
        ColumnDef("created_at", "TIMESTAMP(6)"),
    ]),
    "constatation": TableSchema([
        ColumnDef("payload_index", "BIGINT"),
        ColumnDef("user_id", "BIGINT"),
        ColumnDef("constatation_index", "BIGINT"),
        ColumnDef("label_group", "VARCHAR"),
        ColumnDef("subgroup", "VARCHAR"),
        ColumnDef("tranche_label", "VARCHAR"),
        ColumnDef("start_date", "TIMESTAMP(6)"),
        ColumnDef("end_date", "TIMESTAMP(6)"),
        ColumnDef("trimester_days", "BIGINT"),
        ColumnDef("bill_amount", "DOUBLE"),
        ColumnDef("aid_amount", "DOUBLE"),
        ColumnDef("fee_adjustment_days", "BIGINT"),
        ColumnDef("constatation_id", "BIGINT"),
        ColumnDef("billing_type", "VARCHAR"),
        ColumnDef("trimestre_id", "BIGINT"),
        ColumnDef("fee_adjustment_amount", "DOUBLE"),
        ColumnDef("is_simulation", "BOOLEAN"),
        ColumnDef("created_at", "TIMESTAMP(6)"),
        ColumnDef("updated_at", "TIMESTAMP(6)"),
    ]),
    "trimester": TableSchema([
        ColumnDef("created_at", "TIMESTAMP(6)"),
        ColumnDef("organization_id", "BIGINT"),
        ColumnDef("trimester_id", "BIGINT"),
        ColumnDef("updated_at", "TIMESTAMP(6)"),
        ColumnDef("start_date", "TIMESTAMP(6)"),
        ColumnDef("end_date", "TIMESTAMP(6)"),
        ColumnDef("school_year", "VARCHAR"),
        ColumnDef("index", "BIGINT"),
    ]),
    "transaction": TableSchema([
        ColumnDef("transaction_id", "DOUBLE"),
        ColumnDef("created_at", "TIMESTAMP(6)"),
        ColumnDef("updated_at", "TIMESTAMP(6)"),
        ColumnDef("date", "TIMESTAMP(6)"),
        ColumnDef("type_writing", "VARCHAR"),
        ColumnDef("label", "VARCHAR"),
        ColumnDef("user_id", "DOUBLE"),
        ColumnDef("organization_id", "DOUBLE"),
        ColumnDef("service_id", "DOUBLE"),
        ColumnDef("reservation_id", "DOUBLE"),
        ColumnDef("passage_id", "DOUBLE"),
        ColumnDef("incoming_account", "DOUBLE"),
        ColumnDef("outgoing_account", "DOUBLE"),
        ColumnDef("amount", "DOUBLE"),
        ColumnDef("historical_balance", "DOUBLE"),
        ColumnDef("canceled", "BOOLEAN"),
    ]),
    "user_info_school_year": TableSchema([
        ColumnDef("id", "BIGINT"),
        ColumnDef("school_year_id", "BIGINT"),
        ColumnDef("id_user", "DOUBLE"),
        ColumnDef("id_subgroup", "DOUBLE"),
        ColumnDef("bank_detail_id", "DOUBLE"),
        ColumnDef("choice_bank_details", "VARCHAR"),
        ColumnDef("id_tranche", "BIGINT"),
        ColumnDef("label_tranche", "VARCHAR"),
        ColumnDef("label_subgroup", "VARCHAR"),
        ColumnDef("label_group", "VARCHAR"),
        ColumnDef("created_at", "TIMESTAMP(6)"),
        ColumnDef("updated_at", "TIMESTAMP(6)"),
    ]),
}
